### ISSUE TITLE
Adding WebDriver+Chrome server to the Docker Build

### ISSUE THREAD

**Issue by Gill-Bates** [linuxserver/docker-changedetection.io#14]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

The Chrome/Javascript method requires a network connection to a running WebDriver+Chrome server, set by the ENV var 'WEBDRIVER_URL'.

### Reason for change

Using the Screenshot functionality

**Comment by Nosen92** [comment]
Agreed. Many of changedetection's features have the playwright browser as a dependency. Without it changedetection can only detect rudimentary changes, and many advanced features like browser steps, screenshots and logins are unavailable.

**Comment by thespad** [comment]
Playwright won't provide muslc wheels and don't support source builds from pypi which makes life difficult.

Could you try with `docker.io/thespad/playground:changedetection` and see if the playwright element works correctly.

In terms of Chrome we're not going to bundle Chromium in the container as it would basically double the size, and the webdriver depends on it so it's not like we can just install that part of it. If you want to add it yourself you can use https://github.com/linuxserver/docker-mods/tree/universal-package-install to do so based on the available packages here: https://pkgs.alpinelinux.org/packages?name=chromium-chromedriver&branch=v3.19

**Comment by thespad** [comment]
Actually, I was wrong, it nearly triples the size of the image
```
changedetection                      chrome            4c88d381fec0   7 seconds ago    973MB
changedetection                      latest            2a7b3e8b8649   13 minutes ago   366MB
```

**Comment by Nosen92** [comment]
Disappointing that playwright doesn't build. That really clips the wings on changedetection. Thank you for the advice. I'll tinker with it when I find the time.

**Comment by thespad** [comment]
The image I posted has playwright built from source from their git repo. It's a pain but not unworkable if it enables the functionality.
