### ISSUE TITLE
No module named 'playwright' 

### ISSUE THREAD

**Issue by noja11** [linuxserver/docker-changedetection.io#9]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Linking to the Browserless container allows ChangeDetection to monitor screenshots - this is achieved through setting the correct env variable in the container.

## Current Behavior
Searches fail with the statement - No module named 'playwright' - See discussion here: https://github.com/dgtlmoon/changedetection.io/discussions/944 

I switched to the ghcr.io/dgtlmoon/changedetection.io:latest repository and issue resolved.

## Steps to Reproduce

1. 
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by thespad** [comment]
As noted in the readme https://github.com/linuxserver/docker-changedetection.io#application-setup, there are no Alpine builds for Playwright, so we cannot include it, you can either use Selenium in its place or use the official container if you require it.

**Comment by noja11** [comment]
> As noted in the readme https://github.com/linuxserver/docker-changedetection.io#application-setup, there are no Alpine builds for Playwright, so we cannot include it, you can either use Selenium in its place or use the official container if you require it.

Ahh thanks.  Sorry I confess to not having gone through the readme first.  I hadn't needed the snapshot feature yest and when I did, I chose the Browserless app from Unraid's CA and just didn't get further than the issue I linked first.  Sorry for the hassle!
